# Generated by Django 5.0.7 on 2024-08-01 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_url',
            new_name='imageURL',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image_ids',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='issue',
            name='imageIds',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='issue',
            name='issueType',
            field=models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug'), ('Subtask', 'Subtask'), ('Epic', 'Epic')], default='Task', max_length=20),
        ),
        migrations.AddField(
            model_name='label',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
